### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by unsatifsed27** [CipherOS/maintainership#4]
## Device
```
sweet
Redmi Note 10 Pro
Xiaomi
```

## Trees

```
https://github.com/unsatifsed27/device_xiaomi_sweet.git
https://github.com/unsatifsed27/sleepy_kerner_xiaomi_sweet.git
https://github.com/unsatifsed27/vendor_xiaomi_sweet.git
```

## Source patches

```
None
```

## Any bugs

```
No
```

## Unofficial

```
https://t.me/RedmiNote10ProIDUpdate/1167
https://t.me/RedmiNote10ProChannel/989

```

## Usernames

```
https://t.me/UnsatisfedError
https://github.com/unsatifsed27
https://forum.xda-developers.com/m/unsatifsed27
https://sourceforge.net/u/unsatifsed27/profile/
```

## Extra

```
No
```

**Comment by alibei** [comment]
I think you forgot to write anything here

**Comment by techyminati** [comment]
@unsatifsed27

**Comment by unsatifsed27** [comment]
I edited

**Comment by techyminati** [comment]
@unsatifsed27 1.) Drop https://github.com/unsatifsed27/device_xiaomi_sweet/commit/3801008cd881a164ab5af818e9264e0bbfa447d2#diff-ca2abe1f7782e8323aa7579927e9545137d350025d641c750e9829062ef4fcd6R16
We dont have any flag like '''TARGET_SUPPORTS_QUICK_TAP''' also '''TARGET_USES_BLUR''' is depreciated. 

2.) https://github.com/unsatifsed27/device_xiaomi_sweet/commit/3801008cd881a164ab5af818e9264e0bbfa447d2#diff-65803765b59440a7be06b059879f09a5fbca828058d0ecb88a53112bf3ed8684R35 & redefined here https://github.com/unsatifsed27/device_xiaomi_sweet/commit/3801008cd881a164ab5af818e9264e0bbfa447d2#diff-ca2abe1f7782e8323aa7579927e9545137d350025d641c750e9829062ef4fcd6R11 Don't use props since you already have a flag.

3.) https://github.com/unsatifsed27/device_xiaomi_sweet/commit/fa4ee26e7ee763e6b01e7b654a118ad938e35798 nuke/forcepush this commit away.

4.) Drop https://github.com/unsatifsed27/device_xiaomi_sweet/commit/8fec498e990cfe644d0fcca23b489ddbc7e64333

5.) Forcepush this away https://github.com/unsatifsed27/device_xiaomi_sweet/commit/faf06d96b9704c97b61b708e6ef78e30e591a033#diff-151aef4e286613b79b65e512509f8c5b43c20939baff4c9e65e38ab639e0e7a5R8

6.) Fix Authorship https://github.com/unsatifsed27/device_xiaomi_sweet/commit/faf06d96b9704c97b61b708e6ef78e30e591a033#diff-151aef4e286613b79b65e512509f8c5b43c20939baff4c9e65e38ab639e0e7a5R40

OG Commit: https://github.com/sarthakroy2002/device_realme_RMX2020/commit/52d8283cb234fd6444c4f79b4fa33d836a968648

Rest Looks fine to me, fix them and we'll happy to add sweet to OFFICIAL.

**Comment by unsatifsed27** [comment]
I have fixed it, please check again

**Comment by techyminati** [comment]
Everything else fine except this

https://github.com/unsatifsed27/device_xiaomi_sweet/commit/dd4126546c26378439a1b27a93aa5378a45d6ea1#diff-151aef4e286613b79b65e512509f8c5b43c20939baff4c9e65e38ab639e0e7a5R38

Read (6) again.

**Comment by unsatifsed27** [comment]
I have fixed again

**Comment by resist15** [comment]
> I have fixed again

https://github.com/unsatifsed27/device_xiaomi_sweet/commit/8c40d7f55e19db89357d99cb8144914da50b7502

please fix this commit

**Comment by DhruvChhura** [comment]
> What is wrong



> What is wrong

"Disable TTS force stop warning"
This should add one string, but your commits adds other strings as well which should not be there according to your commit message.

**Comment by unsatifsed27** [comment]
> > What is wrong
> 
> > What is wrong
> 
> "Disable TTS force stop warning" This should add one string, but your commit adds other strings as well which should not be there according to your commit message.

I have fixed, please check again

**Comment by techyminati** [comment]
@unsatifsed27 Everything is fine except uh, can you ammend proper authorship to this https://github.com/unsatifsed27/device_xiaomi_sweet/commit/f916ac730a83cecf1dfe69cf955bb91e909b42d9 ? i gave OG author commit in 6th point.

**Comment by unsatifsed27** [comment]
> @unsatifsed27 Everything is fine except uh, can you ammend proper authorship to this [unsatifsed27/device_xiaomi_sweet@f916ac7](https://github.com/unsatifsed27/device_xiaomi_sweet/commit/f916ac730a83cecf1dfe69cf955bb91e909b42d9) ? i gave OG author commit in 6th point.

placing cmd line from initial tree, Is the placement of the new cmd line under the old cmd line?

**Comment by techyminati** [comment]
> > @unsatifsed27 Everything is fine except uh, can you ammend proper authorship to this [unsatifsed27/device_xiaomi_sweet@f916ac7](https://github.com/unsatifsed27/device_xiaomi_sweet/commit/f916ac730a83cecf1dfe69cf955bb91e909b42d9) ? i gave OG author commit in 6th point.
> 
> placing cmd line from initial tree, Is the placement of the new cmd line under the old cmd line?
Just ammend author to 
https://github.com/unsatifsed27/device_xiaomi_sweet/commit/f916ac730a83cecf1dfe69cf955bb91e909b42d9

**Comment by unsatifsed27** [comment]
> > > @unsatifsed27 Everything is fine except uh, can you ammend proper authorship to this [unsatifsed27/device_xiaomi_sweet@f916ac7](https://github.com/unsatifsed27/device_xiaomi_sweet/commit/f916ac730a83cecf1dfe69cf955bb91e909b42d9) ? i gave OG author commit in 6th point.
> > 
> > 
> > placing cmd line from initial tree, Is the placement of the new cmd line under the old cmd line?
> 
> Just ammend author to [unsatifsed27/device_xiaomi_sweet@f916ac7](https://github.com/unsatifsed27/device_xiaomi_sweet/commit/f916ac730a83cecf1dfe69cf955bb91e909b42d9)

Check again

**Comment by resist15** [comment]
All Looks Fine To Me Now Wait For Others To Reply once

**Comment by alibei** [comment]
Seems fine now. I also looked at your unofficial release in TG. Okay from my side

**Comment by techyminati** [comment]
You're accepted , Drop a mail to us on cipher.rom@gmail.com and we'll send invite links to Maintainer Chat.
